server:
  port: 7790
spring:
  application:
    name: webssh
  mvc:
    view:
      prefix: /page/
      suffix: .html
  servlet:
    multipart:
      max-file-size: 1024000KB
      maxRequestSize: 1024000KB

config:
  ssh:
    host: 127.0.0.1
    port: 22
    username: root
    password: opzpy123